name: CI

on:
  push:
  workflow_dispatch:

jobs:
  ghr_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REP_PAT }}

      - name: Define image name
        id: prep
        uses: ./.github/actions/docker-image-tag
        with:
          custom_tag: 'base'

      -  name: Build base image
         uses: docker/build-push-action@v2
         with:
           context: .
           file: ./docker/base.docker
           push: true
           tags: ${{ steps.prep.outputs.custom_tag }}
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: mode=max,type=local,dest=/tmp/.buildx-cache
