name: RELEASE

on:
  release:
  workflow_dispatch:

jobs:
  upload_ofcl_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.POETRY_HTTP_BASIC_PYPI_FASTFM2_TOKEN }}
          repository_url: https://upload.pypi.org/legacy/
          # verbose: true
