name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        python: [37]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@master
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.7.2
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_SKIP: pp*
          CIBW_BEFORE_ALL_LINUX: curl -o cmake312.tar.gz -L https://github.com/Kitware/CMake/releases/download/v3.12.0/cmake-3.12.0.tar.gz && \
                                 tar -zxvf cmake312.tar.gz                                                                                 && \
                                 cd cmake-3.12.0 && ./bootstrap && make && make install                                                    && \
                                 ln -fs /usr/local/bin/cmake /usr/bin/cmake
          CIBW_BEFORE_BUILD: make
          CIBW_BUILD: cp${{ matrix.python }}-*
          CIBW_BUILD_VERBOSITY: 3

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
