name: 'ImageTagger'
description: 'Construct docker image tag based on current branch name'
inputs:
  custom_tag:
    description: 'docker custom tag'
    required: false
outputs:
  tag:
    description: "Image tag"
    value: ${{ steps.imtag-generator.outputs.tags }}
runs:
  using: "composite"
  steps:
    - run: echo Hello from action!
      shell: bash
    - id: imtag-generator
      run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository  }}
          # Change all uppercase to lowercase
          GHCR_IMAGE=$(echo $GHCR_IMAGE | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION_TAG="${GHCR_IMAGE}:${VERSION}"
          CUSTOM_TAG="${GHCR_IMAGE}:${{ inputs.custom_tag }}"
          echo "::set-output name=ghcr_image::${GHCR_IMAGE}"
          echo "::set-output name=version_tag::${VERSION_TAG}"
          echo "::set-output name=custom_tag::${CUSTOM_TAG}"
      shell: bash